### ISSUE TITLE
trouble running `slc run local-server`

### ISSUE THREAD

**Issue by trangiiee** [strongloop/loopback-faq-rest-connector#3]
Hi i'm having trouble running `slc run local-server`. 

This is what I'm getting.

```

slc run local-server
INFO strong-agent v1.6.3 profiling app 'local-server' pid '2946'
INFO strong-agent[2946] started profiling agent
INFO supervisor reporting metrics to `internal:`
supervisor running without clustering (unsupervised)

WARNING: LoopBack connector "rest" is not installed as any of the following modules:

 ./connectors/rest
loopback-connector-rest

To fix, run:

    npm install loopback-connector-rest

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error:
WARNING: LoopBack connector "rest" is not installed as any of the following modules:

 ./connectors/rest
loopback-connector-rest

To fix, run:

    npm install loopback-connector-rest

    at DataSource.setup (/Users/username/projects/node/loopback-faq-rest-connector/local-server/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/datasource.js:304:28)
    at new DataSource (/Users/username/projects/node/loopback-faq-rest-connector/local-server/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/datasource.js:109:8)
    at Registry.createDataSource (/Users/username/projects/node/loopback-faq-rest-connector/local-server/node_modules/loopback/lib/registry.js:349:12)
    at dataSourcesFromConfig (/Users/username/projects/node/loopback-faq-rest-connector/local-server/node_modules/loopback/lib/application.js:387:19)
    at EventEmitter.app.dataSource (/Users/username/projects/node/loopback-faq-rest-connector/local-server/node_modules/loopback/lib/application.js:221:12)
    at /Users/username/projects/node/loopback-faq-rest-connector/local-server/node_modules/loopback-boot/lib/executor.js:160:9
    at /Users/username/projects/node/loopback-faq-rest-connector/local-server/node_modules/loopback-boot/lib/executor.js:251:5
    at Array.forEach (native)
    at forEachKeyedObject (/Users/username/projects/node/loopback-faq-rest-connector/local-server/node_modules/loopback-boot/lib/executor.js:250:20)
    at setupDataSources (/Users/username/projects/node/loopback-faq-rest-connector/local-server/node_modules/loopback-boot/lib/executor.js:159:3)

```

**Comment by crandmck** [comment]
Hi @trangiiee sorry for the (very) late response.  You probably didn't do `npm install` in each of the server directories.  I added these steps to the README.  If you still have a problem, please open another issue.
